# Generated by Django 4.1.4 on 2022-12-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='explicit_url',
            field=models.CharField(blank=True, help_text='Нужно указывать в таком формате - app/желаемый_номер. Номер должен быть свободен', max_length=100, null=True, unique=True, verbose_name='Явный адрес'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название Меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, help_text='Нужно указывать в таком формате - app:new желаемый_номер(пробел обязателен)', max_length=100, null=True, unique=True, verbose_name='Именованный адрес'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem', verbose_name='Родительская таблица'),
        ),
    ]
